# Generated by Django 3.2.7 on 2021-10-02 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('decription', models.CharField(max_length=200)),
                ('dateofcompletion', models.DateField()),
                ('status', models.CharField(choices=[('COMPLETE', 'COMPLETE'), ('NEW', 'NEW')], default='NEW', max_length=9)),
                ('dateofcreation', models.DateTimeField(auto_now_add=True)),
                ('dateofmodification', models.DateField()),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
