# Generated by Django 3.2.7 on 2021-10-02 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dateofmodification',
            field=models.DateField(auto_now=True),
        ),
    ]
