# Generated by Django 3.2.7 on 2021-10-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_alter_task_dateofmodification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dateofcreation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
