# Generated by Django 3.2.7 on 2021-10-02 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Task', '0003_alter_task_dateofcreation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dateofcreation',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='dateofmodification',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='iduser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
