# Generated by Django 3.2.7 on 2021-10-02 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Task', '0004_auto_20211002_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='iduser',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
